/**
 * Roles and permissions.
 *
 * Authorization is centralised here so new roles/permissions can be added
 * without touching call sites (requirement §10). The API layer always
 * enforces these server-side; frontend guards are UX only.
 */

export const ROLES = {
  PARENT: "PARENT",
  STUDENT: "STUDENT",
  TUTOR: "TUTOR",
  ADMIN: "ADMIN",
};

export const ROLE_LABELS = {
  PARENT: "Parent",
  STUDENT: "Student",
  TUTOR: "Tutor",
  ADMIN: "Administrator",
};

/** Roles that book lessons (the "demand" side of the marketplace). */
export const LEARNER_ROLES = [ROLES.PARENT, ROLES.STUDENT];

export const PERMISSIONS = {
  // Own profile
  PROFILE_VIEW: "PROFILE_VIEW",
  PROFILE_EDIT: "PROFILE_EDIT",

  // Children
  CHILD_MANAGE: "CHILD_MANAGE",

  // Tutor profile / onboarding
  TUTOR_PROFILE_EDIT: "TUTOR_PROFILE_EDIT",
  TUTOR_AVAILABILITY_EDIT: "TUTOR_AVAILABILITY_EDIT",
  TUTOR_EARNINGS_VIEW: "TUTOR_EARNINGS_VIEW",
  TUTOR_PAYOUT_MANAGE: "TUTOR_PAYOUT_MANAGE",

  // Bookings
  BOOKING_VIEW: "BOOKING_VIEW",
  BOOKING_CREATE: "BOOKING_CREATE",
  BOOKING_CANCEL: "BOOKING_CANCEL",
  BOOKING_COMPLETE: "BOOKING_COMPLETE",

  // Payments
  PAYMENT_VIEW: "PAYMENT_VIEW",

  // Messaging
  MESSAGE_VIEW: "MESSAGE_VIEW",
  MESSAGE_SEND: "MESSAGE_SEND",

  // Requests & matching
  REQUEST_CREATE: "REQUEST_CREATE",
  REQUEST_VIEW: "REQUEST_VIEW",
  REQUEST_RESPOND: "REQUEST_RESPOND",

  // Favourites
  FAVOURITE_MANAGE: "FAVOURITE_MANAGE",

  // Reviews
  REVIEW_CREATE: "REVIEW_CREATE",
  REVIEW_VIEW: "REVIEW_VIEW",

  // Notifications
  NOTIFICATION_VIEW: "NOTIFICATION_VIEW",

  // Disputes
  DISPUTE_CREATE: "DISPUTE_CREATE",

  // Requests & matching — owner side
  REQUEST_EDIT: "REQUEST_EDIT",

  // Progress reports (§41 Phase 2)
  PROGRESS_REPORT_WRITE: "PROGRESS_REPORT_WRITE",
  PROGRESS_REPORT_VIEW: "PROGRESS_REPORT_VIEW",

  // Admin
  ADMIN_USER_MANAGE: "ADMIN_USER_MANAGE",
  ADMIN_REQUEST_MODERATE: "ADMIN_REQUEST_MODERATE",
  ADMIN_PROGRESS_VIEW: "ADMIN_PROGRESS_VIEW",
  ADMIN_TUTOR_REVIEW: "ADMIN_TUTOR_REVIEW",
  ADMIN_VERIFICATION_MANAGE: "ADMIN_VERIFICATION_MANAGE",
  ADMIN_CURRICULUM_MANAGE: "ADMIN_CURRICULUM_MANAGE",
  ADMIN_BOOKING_MANAGE: "ADMIN_BOOKING_MANAGE",
  ADMIN_PAYMENT_MANAGE: "ADMIN_PAYMENT_MANAGE",
  ADMIN_PAYOUT_MANAGE: "ADMIN_PAYOUT_MANAGE",
  ADMIN_DISPUTE_MANAGE: "ADMIN_DISPUTE_MANAGE",
  ADMIN_REVIEW_MODERATE: "ADMIN_REVIEW_MODERATE",
  ADMIN_MESSAGE_MODERATE: "ADMIN_MESSAGE_MODERATE",
  ADMIN_PROMOTION_MANAGE: "ADMIN_PROMOTION_MANAGE",
  ADMIN_RISK_MANAGE: "ADMIN_RISK_MANAGE",
  ADMIN_ANALYTICS_VIEW: "ADMIN_ANALYTICS_VIEW",
  ADMIN_SETTINGS_MANAGE: "ADMIN_SETTINGS_MANAGE",
  /**
   * External modules — provider credentials, webhook secrets, connection
   * tests. Held apart from ADMIN_SETTINGS_MANAGE on purpose: editing the
   * footer copy and rotating the Stripe secret key are not the same act, and
   * a future limited-administrator role should be able to do the first
   * without being able to do the second (§36).
   */
  ADMIN_INTEGRATION_MANAGE: "ADMIN_INTEGRATION_MANAGE",
};

const LEARNER_PERMISSIONS = [
  PERMISSIONS.PROFILE_VIEW,
  PERMISSIONS.PROFILE_EDIT,
  PERMISSIONS.BOOKING_VIEW,
  PERMISSIONS.BOOKING_CREATE,
  PERMISSIONS.BOOKING_CANCEL,
  PERMISSIONS.PAYMENT_VIEW,
  PERMISSIONS.MESSAGE_VIEW,
  PERMISSIONS.MESSAGE_SEND,
  PERMISSIONS.REQUEST_CREATE,
  PERMISSIONS.REQUEST_EDIT,
  PERMISSIONS.REQUEST_VIEW,
  PERMISSIONS.FAVOURITE_MANAGE,
  PERMISSIONS.REVIEW_CREATE,
  PERMISSIONS.REVIEW_VIEW,
  PERMISSIONS.NOTIFICATION_VIEW,
  PERMISSIONS.DISPUTE_CREATE,
  // Families read progress reports; only the tutor who wrote one may change it.
  PERMISSIONS.PROGRESS_REPORT_VIEW,
];

export const ROLE_PERMISSIONS = {
  [ROLES.PARENT]: [...LEARNER_PERMISSIONS, PERMISSIONS.CHILD_MANAGE],

  // A self-serve student books for themselves and has no children to manage.
  [ROLES.STUDENT]: [...LEARNER_PERMISSIONS],

  [ROLES.TUTOR]: [
    PERMISSIONS.PROFILE_VIEW,
    PERMISSIONS.PROFILE_EDIT,
    PERMISSIONS.TUTOR_PROFILE_EDIT,
    PERMISSIONS.TUTOR_AVAILABILITY_EDIT,
    PERMISSIONS.TUTOR_EARNINGS_VIEW,
    PERMISSIONS.TUTOR_PAYOUT_MANAGE,
    PERMISSIONS.BOOKING_VIEW,
    PERMISSIONS.BOOKING_CANCEL,
    PERMISSIONS.BOOKING_COMPLETE,
    PERMISSIONS.MESSAGE_VIEW,
    PERMISSIONS.MESSAGE_SEND,
    PERMISSIONS.REQUEST_VIEW,
    PERMISSIONS.REQUEST_RESPOND,
    PERMISSIONS.REVIEW_VIEW,
    PERMISSIONS.NOTIFICATION_VIEW,
    PERMISSIONS.DISPUTE_CREATE,
    PERMISSIONS.PROGRESS_REPORT_WRITE,
    PERMISSIONS.PROGRESS_REPORT_VIEW,
  ],

  [ROLES.ADMIN]: Object.values(PERMISSIONS),
};

export function permissionsForRole(role) {
  return ROLE_PERMISSIONS[role] ?? [];
}

export function roleHasPermission(role, permission) {
  return permissionsForRole(role).includes(permission);
}
